### ISSUE TITLE
feature: support arm

### ISSUE THREAD

**Issue by ruscon** [syndikat7/mongodb-rust-ping#5]
https://stackoverflow.com/a/66875783

Please :)

**Comment by ruscon** [comment]
@Anubiso thanks!

FYI, there is a https://github.com/cross-rs/cross project

**Comment by lasseoe** [comment]
@ruscon similar project with darwin arm64 binaries, https://github.com/lasseoe/mongodb-k8s-probe

**Comment by Anubiso** [comment]
@ruscon 
Just to get this right: on which architecture are you trying to execute this? Because the v0.3.1 is working on our Apple Silicon Machines: 
![image](https://github.com/user-attachments/assets/51a6a073-c5f5-4b96-b37f-326de5755651)
![image](https://github.com/user-attachments/assets/0d42b12a-5623-45bb-95b0-09182aa69c79)

And the linux_x64 is working in the k8s context.

**Comment by Anubiso** [comment]
@ruscon We saw your example and could confirm that the apple_arm64 binary was not executable in this linux_arm64 context. We now enhanced our pipelines (also thanks to your hint for cross) and also provide a linux_arm64 which can be used in this context:

Dockerfile:
`FROM mongo:6.0
RUN apt-get update  \
    && apt-get install -y --no-install-recommends wget \
    && rm -rf /var/lib/apt/lists/*

RUN wget ./mongodb-rust-ping.tar.gz "https://github.com/syndikat7/mongodb-rust-ping/releases/download/v0.3.9/mongodb-rust-ping-aarch64-unknown-linux-gnu.tar.gz"  -O - | tar -xzv  && chmod +x mongodb-rust-ping`

**Comment by ruscon** [comment]
`aarch64-unknown-linux-gnu` works perfect for me, thanks
